[package]
name = "todoist"
version = "0.1.0"
authors = ["Shuhei Yamashita <shuhei.yamashita@ozinter.jp>"]

[dependencies]
reqwest = "0.5.1"
serde = "1.0.2"
serde_derive = "1.0.2"
serde_json = "1.0"
chrono = "0.4"
slack-hook = "0.6"

[dependencies.url]
git = "https://github.com/servo/rust-url"